apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  # App resources
  - app-services/backend
  - app-services/frontend
  - app-services/postgres
  - app-services/vault
  - app-services/cert-manager
  - app-services/ingress
