apiVersion: apps/v1
kind: Deployment
metadata:
  name: zyoud-frontend
  namespace: zyoud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zyoud-frontend
  template:
    metadata:
      labels:
        app: zyoud-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/zyouud/apptraining/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          env:
            - name: PORT
              value: "4200"
            # Frontend will call backend through ingress later (Step 7),
            # keep domain as base URL (your frontend uses /api/...).
            - name: REACT_APP_API_URL
              value: "https://devops-3.sociumtech.com"

