apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/zyouud/apptraining-backend
    newTag: "dev"
  - name: ghcr.io/zyouud/apptraining-frontend
    newTag: "dev"

